name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:               
  build:
    name: Test
    strategy:
      matrix:
        go-version: [1.14.x, 1.15.x, tip]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-go@v2.1.3
      - uses: actions/checkout@v2
      
      - name: Run local test Server
        run: |
          docker run -d -p 3735:3735 etesync/test-server:latest
          ./scripts/wait-for-it.sh localhost:3735
          
      - name: Tests
        env:
          ETEBASE_TEST_HOST: localhost:3735
        run: go test -race -coverprofile=coverage.txt -covermode=atomic ./...
      
      - name: Codecov
        run: bash <(curl -s https://codecov.io/bash)
