name: Go

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
       - name: fmt
         run: go fmt ./...
       - name: vet
         run: go vet ./...
