name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2.1.3
      - uses: actions/checkout@v2
      - name: fmt
        run: go fmt ./...
      - name: vet
        run: go vet ./...
