name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:               
  build:
    name: CI
    strategy:
      matrix:
        go-version: [1.14.x, 1.15.x, tip]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-go@v2.1.3
      - uses: actions/checkout@v2
      - run: |
          docker pull victorrds/etebase
          docker run -d -v $PWD/scripts:/etebase/scripts -e DEBUG=true -p 80:3735 victorrds/etebase ./scripts/testmode.sh
          ./scripts/wait-for-it.sh localhost:80
      - run: go fmt ./...
      - run: go vet ./...
      - run: ETEBASE_TEST_HOST=localhost:80 go test -race -coverprofile=coverage.txt -covermode=atomic ./...
      - run: bash <(curl -s https://codecov.io/bash)
