name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  etebase-server:
    runs-on: ubuntu-latest
    services:
      etebase: 
        image: victorrds/etebase
           
  build:
    name: CI
    strategy:
      matrix:
        go-version: [1.14.x, 1.15.x, tip]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-go@v2.1.3
      - uses: actions/checkout@v2
      - run: go fmt ./...
      - run: go vet ./...
      - run: go test ./...
